---
AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation CI/CD Demo

Parameters:
  Stage:
    Type: String
    Default: dev
  VPCCidrBlock:
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Configuration
        Parameters:
          - Stage
      - Label:
          default: Network Configuration
        Parameters:
          - VPCCidrBlock

    ParameterLabels:
      Stage:
        default: Stage
      VPCCidrBlock:
        default: VPC Cidr Block

Resources:

  NW:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/network.yml
      Parameters:
        Stage: !Ref Stage
        VPCCidrBlock: !Ref VPCCidrBlock

  SG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/security_group.yml
      Parameters:
        Stage: !Ref Stage
        VpcId: !GetAtt NW.Outputs.VpcId
