---
AWSTemplateFormatVersion: 2010-09-09
Description: Security Group Stack

Parameters:
  Stage:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Configuration
        Parameters:
          - Stage
      - Label:
          default: Security Group Configuration
        Parameters:
          - VpcId
    ParameterLabels:
      Stage:
        default: Stage
      VpcId:
        default: VpcId

Resources:
  SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable ssh and web access
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${Stage}-sg

Outputs:
  SGId:
    Value: !Ref SG
